baseURL: "http://example.org/"
languageCode: "en-us"
theme: "default"
defaultContentLanguageInSubdir: true
ignoreFiles: ["\\*.keep$"] # doesn't work due to Hugo bug.

languages:
  pl:
    languageName: "Polski"
    weight: 1
    title: "Strona Domowa"
    taxonomies:
      tag: "tagi"
      kategoria: "kategorie"
    menu:
      main:
      - identifier: index
        name: Strona główna
        url: .
        weight: -100
      - identifier: about
        name: O mnie
        url: ./about/
        weight: -50
      - identifier: blog
        name: Blog
        url: ./blog/
      - identifier: gallery
        name: Galeria
        url: ./gallery/
  en:
    languageName: "English"
    weight: 2
    title: "Homepage"
    taxonomies:
      tag: "tags"
      category: "categories"
    menu:
      main:
      - identifier: index
        name: Index
        url: .
        weight: -100
      - identifier: about
        name: About
        url: ./about/
        weight: -50
      - identifier: blog
        name: Blog
        url: ./blog/
      - identifier: gallery
        name: Gallery
        url: ./gallery/
  de:
    languageName: "Deutsch"
    weight: 3
    title: "Startseite"
    taxonomies:
      das etikett: "die etikette"
      die kategorie: "die kategorien"
    menu:
      main:
      - identifier: index
        name: Index DE
        url: .
        weight: -100
      - identifier: about
        name: About DE
        url: ./about/
        weight: -50
      - identifier: blog
        name: Blog DE
        url: ./blog/
      - identifier: gallery
        name: Galeria DE
        url: ./gallery/

